
# EXTRA_CFLAGS := -D DEBUG		# all .c files will define DEBUG
# CFLAGS_sub3.o := -D DEBUG_SUB3  # only sub3.c file will define DEBUG_SUB3

obj-y += KAL_LEDDevice.o
obj-y += KAL_UARTDevice.o
obj-y += KAL_KEYDevice.o