
# EXTRA_CFLAGS := -D DEBUG		# all .c files will define DEBUG
# CFLAGS_sub3.o := -D DEBUG_SUB3  # only sub3.c file will define DEBUG_SUB3

obj-y += led_device.o
obj-y += uart_device.o
obj-y += uart_ringbuffer.o
obj-y += input_buffer.o
obj-y += input_system.o
obj-y += key_device.o
